### ISSUE TITLE
Fatal error in plugin view PHP 7.1+

### ISSUE THREAD

**Issue by MattHarbert** [WordPress/classic-editor#71] opened 2019-01-16 20:11 UTC
When viewing all of the plugins in Wordpress, this plugin creates a fatal error in PHP 7.1+ (works 7.0 and below) that causes the plugins page to break. "[] operator not supported for strings" is the error thrown.

**Comment by azaozz** [comment] 2019-01-25 20:54
Yeah, that's been reported a few times. Will be fixed in the next release. It's caused by another plugin that is "behaving badly" (doesn't use that filter properly).

Thanks :)

**Closed by azaozz** 2019-01-25 20:54 UTC
