### ISSUE TITLE
dropdown list of paragraph does not show anything

### ISSUE THREAD

**Issue by ComputingFroggy** [WordPress/classic-editor#101] opened 2019-06-25 17:32 UTC
I am running WP 5.2.2 with the _Classic Editor_ plugin v. 1.5.
If I have a lot of text in the article that makes me scroll down, when, at the bottom of the article, I click on the dropdown list of the paragraph (to, for instance, change to "Title 2") no list is displayed.
I have to scroll to the top of the article for the dropdown list to be displayed. Then I change the paragraph type and I scroll down to carry on working ... not the easiest way to work !

**Comment by azaozz** [comment] 2019-07-08 20:02
Cannot reproduce this even with a "huge" post of 60,000 words. Things get slow and a bit choppy but all drop-downs seem to work.

May be some sort of a CSS error where the bottom of the post is "outside" the editor container, so the drop-down position is not calculated correctly. Can you try investigating it a bit more:
1. After how many paragraphs the drop-down doesn't show properly.
2. Is this the same when trying different browsers or in a private tab in the same browser.

If this continues to happen, could you [post to the support forum](https://wordpress.org/support/plugin/classic-editor/) with the above info. Closing this as it is not a problem with the plugin, rathar it seems like a problem on the (old) Edit Post screen.

**Closed by azaozz** 2019-07-08 20:02 UTC
