### ISSUE TITLE
Publish date is wrong

### ISSUE THREAD

**Issue by lreisoliveira** [WordPress/classic-editor#110] opened 2020-02-11 12:29 UTC
Hello

When the plugin classic editor is **inactive**, the publish date show correctly. 

![publish_date_ok](https://user-images.githubusercontent.com/10522957/74236172-7094a900-4caf-11ea-884c-8eeb0e4fe302.png)

**When the plugin is **active**, the publish date show is wrong.**
![publish_date_wrong](https://user-images.githubusercontent.com/10522957/74235970-ec422600-4cae-11ea-8e30-3d8eb9005733.png)

That happens only in the area wp-admin. The datetime in frontend is correct.
The timezone and the date system are also correct 

The post date original is 2020-02-10 16:54:21
Classic editor version: 1.5
date_default_timezone_set('America/Sao_Paulo');
PHP 7.3
Wordpress 5.3.2
Xubuntu Linux

**Comment by azaozz** [comment] 2020-07-20 18:12
Looks like a problem on the (old) Edit Post screen. Please open a ticket on trac if you can reproduce it with all plugins disabled.

Closing it here as this is unrelated to the plugin.

**Closed by azaozz** 2020-07-20 18:12 UTC
