### ISSUE TITLE
Allow choosing the preferred editor per user

### ISSUE THREAD

**Issue by youknowriad** [WordPress/classic-editor#9] opened 2018-11-19 08:02 UTC
At the moment, the classic editor is a yes/no plugin. It allows you to choose the default editor for all users but as Gutenberg gets rolled-out into Core and plugins add support for it, users would want to start opting in into Gutenberg iteratively. (Similar to how Gutenberg Ramp plugin does). 

**Proposal**

 - Let's try to add more options to the classic editor plugin, the first one could be to allow specific users to choose their preferred editor.

**Mockups**

![switching in classic](https://user-images.githubusercontent.com/272444/48693435-c0361300-ebd9-11e8-832b-2bf818bc1915.png)
![switching in gutenberg](https://user-images.githubusercontent.com/272444/48693436-c0cea980-ebd9-11e8-9cfb-80d2c46748a9.png)
![writing settings](https://user-images.githubusercontent.com/272444/48693437-c0cea980-ebd9-11e8-875b-19998001a9cf.png)

cc @alexislloyd @azaozz

**Comment by azaozz** [comment] 2018-11-19 08:55
Yep, looking at that too. We cannot use the Settings -> Writing screen for the Classic Editor settings as these are accessible only for admins. Also, added another (very requested) feature to "remember" which editor was used for each post and open it next time.

The plan (for now):
- Move the settings to the User Profile screen. It is accessible by all users. We already have a checkbox there to "Disable the visual editor when writing" (that only affects the Classic editor, perhaps we need to make that clear?). Also, we don't let "contributors" click that checkbox (it's not shown), thinking we should do the same for the Classic Editor plugin settings.
- Add two sets of "settings", one for admins, to set site-wide defaults, another for all users to choose whether to use only Classic or switch between Classic/Block editors.

**Comment by alexislloyd** [comment] 2018-11-19 16:36
> We already have a checkbox there to "Disable the visual editor when writing" (that only affects the Classic editor, and other places where wp_editor() is used, including by plugins. Perhaps we need to make that clear?)
As a user, I'm not sure what this means or does. Can we clarify? 
Also, does "block editor" in the settings page refer to Gutenberg? If so, maybe we could say "block editor (Gutenberg)" to make it clear.

Here are two mockups that I think point to what you're suggesting:

User editor settings in the profile screen
![profile-screen](https://user-images.githubusercontent.com/3238155/48721157-5294e180-ebef-11e8-8f31-dc92480f29d6.png)

Admin editor settings in the Writing prefs screen
![admin-screen](https://user-images.githubusercontent.com/3238155/48721168-588ac280-ebef-11e8-952e-83f9473dc097.png)

And I think you're proposing using this UI (from Classic Editor plugin) to allow for starting a post with one editor or the other.
![image](https://user-images.githubusercontent.com/3238155/48721019-05b10b00-ebef-11e8-8878-14b0adc90092.png)

Is there no way to switch once you're writing a post and not lose formatting? My concern is that the drop down above isn't necessarily very discoverable.

**Comment by azaozz** [comment] 2018-11-20 14:57
Uh, sorry about that, should have added few screenshots :)

> As a user, I'm not sure what this means or does. Can we clarify?

The "Disable the visual editor when writing" checkbox is an age-old setting left over from when we implemented TinyMCE. That's WP 2.0! Some people really hated the "Visual Editor" then, and wanted none of it! I know, same story :)

We tried removing it few years ago but got pretty angry requests to put it back (people were still using it). Don't think it makes sense any more, but.... Maybe in 5.1?

> Also, does "block editor" in the settings page refer to Gutenberg? If so, maybe we could say "block editor (Gutenberg)" to make it clear.

Yes, afaik "Gutenberg" is the project name, once merged it will be simply the "Block Editor". There is no mention of Gutenberg in core even in the code.

The last screenshot above is from Gutenberg. It doesn't exist in the Block Editor in core. Currently this plugin adds menu sub-items to Posts, Pages (and any other menus for CPTs that support the Block Editor). It doesn't add "Classic Editor" as a drop-down to the Add New link in the title. 

![1](https://user-images.githubusercontent.com/743931/48779847-31acb900-ece1-11e8-9964-16a8f104028b.png)
"Add New (Classic Editor)" submenu items for Posts and Pages. Always visible. Will also be there for other CPTs that support the Block Editor.

![2](https://user-images.githubusercontent.com/743931/48779999-82241680-ece1-11e8-9ab2-246db743e346.png)
When editing an existing post two other submenu items are added: "Edit in Block Editor" and "Edit in Classic Editor". Visible only when editing a post or a page.

![3](https://user-images.githubusercontent.com/743931/48780140-dcbd7280-ece1-11e8-998e-1b37e8f0fc57.png)
The same submenu items are visible regardless of the editor used.

![4](https://user-images.githubusercontent.com/743931/48780192-024a7c00-ece2-11e8-9006-48392cace748.png)
On the Posts and Pages screens (and other screens for CPTs) there is no drop-down instead of the "Add New" link in the title. There are "Block Editor" and "Classic Editor" action links (visible on hover) for each post/page/CPT.

![5](https://user-images.githubusercontent.com/743931/48780339-5a817e00-ece2-11e8-8ee0-744882001695.png)
The current "admin options" for the Classic Editor plugin. Note that they cannot be moved to the top of the page, this is a limitation in WP (plugins can add their settings only at specific locations so the default WP settings are more consistent).

![6](https://user-images.githubusercontent.com/743931/48780454-9c122900-ece2-11e8-8706-5822fb1526bd.png)
The current settings on the Profile screen. Again, cannot be at the top, WP doesn't allow it.

![7](https://user-images.githubusercontent.com/743931/48780530-ce238b00-ece2-11e8-8ded-95c122f779c9.png)
The "Remember whether the Block or the Classic editor was used for each post and..." checkbox is disabled when that setting doesn't make sense.

This is all of the current UI. Another option that was requested is to choose to open only pages in the Block editor or only posts (i.e. choose by post_type). Can add that too.

Currently the settings use radio buttons. Can switch them to a drop-down (but there will be only one item in the drop-down?). Will change the "Allow users to switch editors" to radio buttons shortly.

(BTW, seems the code here hasn't synced with the plugins repo yet, and for some reason I don't have access to sync it. The updated plugin is in the plugins repo.)

**Comment by azaozz** [comment] 2018-11-20 15:32
Forgot to mention. Alternatively we can make a separate page for the Classic Editor plugin settings, perhaps for admins only. Will be a bit empty, but then we can do anything we want there, i.e. the settings will be at the top, and can add more explanations, text, etc.

**Comment by youknowriad** [comment] 2018-11-21 16:32
@azaozz 

Is in it possible to implement the editor switch as a metabox for the classic editor and as a more menu plugin for Gutenberg like suggested by @alexislloyd ? Any technical reason making this difficult to do?

I also find the links "Edit in *" and "Add New (*)" in the sidebar menu a bit confusing (especially the Edit ones as it's not obvious which post is this referring too). It also overloads this menu a lot.

**Comment by alexislloyd** [comment] 2018-11-21 16:36
@azaozz Thanks for sharing the screenshots! 

I had the same questions that @youknowriad mentioned. I would love to avoid too much clutter in the navigation menu. Especially on the "edit" links, we would be breaking a fundamental UX pattern — nav menu actions are global, actions specific to the post / page are in the post / page editor.

> Yes, afaik "Gutenberg" is the project name, once merged it will be simply the "Block Editor". There is no mention of Gutenberg in core even in the code.

👍Right, makes sense.

> The "Disable the visual editor when writing" checkbox is an age-old setting left over from when we implemented TinyMCE. That's WP 2.0! Some people really hated the "Visual Editor" then, and wanted none of it! I know, same story :)

Wow! Great context, thank you.

**Comment by azaozz** [comment] 2018-11-21 18:20
> nav menu actions are global, actions specific to the post / page are in the post / page editor.

Right. Sure, lets move the "Edit in Block editor" and "Edit in Classic editor". Added them there to have both available regardless of which editor is used but this is not that necessary.

The only thing I'm a bit concerned about is the postbox. These are harder to discover (can be hidden, closed, moved...). On the other hand, the worst case is we get a few more help requests like "My plugin is broken! Can't switch editors" :)

Thinking we should keep the "Add New (Classic)" though. It is where the original "Add New" is and will show for posts, pages, and all other post types on all screens. Don't really see another good/suitable place for it.

> Any technical reason making this difficult

Don't think so but still have to look it up how to add to the Block Editor main menu. Might ping you for a quick help when I get there :)

**Comment by azaozz** [comment] 2018-11-25 22:02
As of https://github.com/WordPress/classic-editor/commit/6bbabe069f243aa83a82bbcba6bc3f2f817b46a8:

- Added [the metabox](https://user-images.githubusercontent.com/272444/48693435-c0361300-ebd9-11e8-832b-2bf818bc1915.png) to switch to the Block Editor (on change).
- Changed the admin settings as per the above mockup.
- Removed the "Edit in ..." links from the menu.

Tried to add the [link to Classic Editor](https://user-images.githubusercontent.com/272444/48693436-c0cea980-ebd9-11e8-9cfb-80d2c46748a9.png) under the Options menu item in the Block Editor but seems impossible (for now). That menu is "locked" for plugin. Will keep looking for alternatives.

Currently the admin settings look like:
![admin-settings](https://user-images.githubusercontent.com/743931/48985230-1b05c800-f10e-11e8-8a9e-85c6df21b8c1.png)

Wondering if we want some more help/context, perhaps something like:
![admin-settings-alt](https://user-images.githubusercontent.com/743931/48985260-615b2700-f10e-11e8-9311-a3b2b75f91d8.png)

**Comment by youknowriad** [comment] 2018-11-27 08:31
Thanks for the update @azaozz Some questions:

 - When the classic editor is chosen as default and the "allow users to switch editors" is checked why the metabox is hidden?

 - How do we choose the editor per user? This is not implemented yet right?

**Comment by azaozz** [comment] 2018-11-27 08:42
> When the classic editor is chosen as default and the "allow users to switch editors" is checked why the metabox is hidden?

When the Classic Editor is chosen it completely disables the Block Editor. There is no point in showing the metabox.

> How do we choose the editor per user? This is not implemented yet right?

It is implemented. The per-user settings are on the Profile screen for each user  (like in the [mockup](https://user-images.githubusercontent.com/3238155/48721157-5294e180-ebef-11e8-8f31-dc92480f29d6.png)) and override the defaults. The only difference is they are not at the top as WP doesn't allow plugins to add settings there :)

**Comment by youknowriad** [comment] 2018-11-27 08:43
> When the Classic Editor is chosen it completely disables the Block Editor. There is no point in showing the metabox.

I'm not sure I understand the reasoning here. If you want to completely disable the editor, you'd uncheck "Allow the users to switch editors". I can see a use-case where we want the classic editor as default for all users but allowing the users to use Gutenberg if they want.

**Comment by youknowriad** [comment] 2018-11-27 08:46
@azaozz I just tested the user preference, it works great but it suffers from the same issue for me. If as a user I choose "classic editor" as my default editor, it doesn't mean I don't want to switch to the block editor from time to time (the metabox should be shown IMO and the preferred editor choice shouldn't not affect the visibility of the metabox)

**Comment by azaozz** [comment] 2018-11-27 08:46
Right that's exactly how it works at the moment :)

- The admins can set defaults for the site.
- The admins can decide whether to allow the users to change the default settings.
- The users can either use these default settings or change them from their Profile if the admins allowed that.

**Comment by youknowriad** [comment] 2018-11-27 09:48
> The main purpose of this plugin is to (completely) disable the Block Editor. This is the default setting after installation.

I agree with this and I'm not suggesting any change here.

But instead of adding a third option, my preference would be to just leverage the existing options but change their default values.

On a new install:

 - Classic editor should be the default editor
 - The "Allow the users to switch editors" should say "No"

This way users won't be able to access the block editor at all.

If you switch the "Allow the users to switch editors" to "Yes". Users should be able to switch editors permanently (using the preference) or temporarily (using the metabox and link). And this no matter the default editor selected.

---
That would be my preference.

**Comment by azaozz** [comment] 2018-11-27 09:49
The only thing remaining is to add the submenu item to the Block Editor main (popout) menu as in the [above mockup](https://user-images.githubusercontent.com/272444/48693436-c0cea980-ebd9-11e8-9cfb-80d2c46748a9.png). 

Unfortunately this is not possible at the moment, it requires https://github.com/WordPress/gutenberg/pull/12309 to be merged. The (mini) plugin for Gutenberg that adds the submenu is already included here but not enabled while waiting for the above PR.

Thinking we need a fallback plan here in case #12309 doesn't make it in WP 5.0. What to do about the "Switch to the Classic Editor" link in the Block Editor. It would be a pretty big regression to not have it, but then there's no way to add it inside the Block Editor... That pretty much leaves only the main WP menu and the admin toolbar, none of them seem a good choice though :(

@alexislloyd @youknowriad any ideas/thoughts?

**Comment by youknowriad** [comment] 2018-11-27 09:54
@azaozz Did you check how "Divi" adds their link to the Gutenberg's toolbar. It's probably a DOM hack but could be a temporary solution before WordPress/gutenberg#12309 lands. 

Also, I'm not certain it's very critical for 5.0 as 5.0.1 will probably happen very quickly after and in the meantime, the preference in the user profile is an alternative.

**Comment by azaozz** [comment] 2018-11-27 10:05
> If you switch the "Allow the users to switch editors" to "Yes". Users should be able to switch editors permanently (using the preference) or temporarily (using the metabox and link). And this no matter the default editor selected.

Right, this is exactly how it works now. The thing is that the settings seem a bit confusing imho. The plugin has two options:
- Completely disable the Block Editor and replace it with the Classic Editor (default).
- Make it possible to use both the Block and the Classic editors side by side.

These settings can be changed by an admin on the Settings->Writing screen, and by any user with role > subscriber on their Profile screen.

However, for clarity, instead of "Default Editor" they should probably be "Disable the Block Editor" and "Use both the Block Editor and the Classic Editor" (as they were before the UI change).

> It's probably a DOM hack but...
The problem is that this is a "high visibility" plugin made by the "core team". There will probably be many many plugins copying code from it. Adding anything even a little "hacky" would send the wrong message :)

**Comment by youknowriad** [comment] 2018-11-27 10:14
> Right, this is exactly how it works now. The thing is that the settings seem a bit confusing imho

In my testing, that's not how it works. because if I choose the "Classic Editor" as default editor, Users can't switch editors no matter what this option says.

I personally think the options are clear, it's the behavior that it's not.

**Comment by azaozz** [comment] 2018-11-27 10:15
Hmm, OK, which option should completely disable the Block Editor?

**Comment by azaozz** [comment] 2018-11-27 10:48
> > The unclear part here is that the user is not choosing a "default editor". They are choosing whether to disable the Block Editor :)

> Is that really important if the default experience does the same thing?

Yep, I think it is. Disabling one editor is not the same as setting the other as default.

To turn that from a "negative" (Disable...) to a positive (Enable/Use...), best would be to add another option [as suggested above](https://github.com/WordPress/classic-editor/issues/9#issuecomment-442000389): 
- Use only the Classic Editor (default)
- Use only the Block Editor
- Use both the Classic and the Block editors.

**Comment by youknowriad** [comment] 2018-11-27 11:45
> Do we want to let users disable the Block Editor, or only admins?

In my mind only admins, if the admin allows the users to switch. Why a user would disable it for itself? not really useful IMO.

**Comment by youknowriad** [comment] 2018-11-27 11:46
> Actually, thinking we should do that. It makes the settings a lot clearer imho. It will also let users (from the Profile screen) choose to only use the Block Editor, that's currently not possible.

I'm fine with this option if it's the only option. We don't need other checkboxes in this case. I'm more interested in clarity.

**Comment by azaozz** [comment] 2018-11-27 17:36
Done in https://github.com/WordPress/classic-editor/commit/e5ff7ae0a6ecae4a3a1c322b446673723a9d36a1.

Currently the admin settings look like:
![admin-settings](https://user-images.githubusercontent.com/743931/49100038-a18be800-f27b-11e8-8db4-42c334bc164b.png)

The user settings are:
![user-settings](https://user-images.githubusercontent.com/743931/49100061-ac467d00-f27b-11e8-9a29-1f5d70fa0b7f.png)

**Comment by youknowriad** [comment] 2018-11-27 20:48
I'm really sorry for the back and forth but actually, it's still confusing to me when testing. I don't understand what "both editors in the default editor choice means and what does "Allow users to switch" option means in this context as well.

I still think my ideal options are these:

1- In the settings screen (for admins), have these two options:

- Choose the default editor: Two choices classic or block.
- Choose whether to allow the users to switch editors or not (force the default editor on all users, on allow them to change their default editor)

By default, I'd say the default editor should say "classic" and the second option should say "no" which means that for all users, the classic editor will be enforced.



2- In the users's profile screen, there's nothing unless the "allow users to switch editors says "yes", in which case each user would be able to choose his own default editor.

3- In the editor screens (both) there's no way to switch editors unless the admin checked the "allow users to switch editors". Changing the editor using this UI is not persistent.

Does that make sense? Thoughts @alexislloyd ?

**Comment by alexislloyd** [comment] 2018-11-27 21:08
> 1- In the settings screen (for admins), have these two options:
> 
> Choose the default editor: Two choices classic or block.
> Choose whether to allow the users to switch editors or not (force the default editor on all users, on allow them to change their default editor)
> By default, I'd say the default editor should say "classic" and the second option should say "no" which means that for all users, the classic editor will be enforced.
> 
> 2- In the users's profile screen, there's nothing unless the "allow users to switch editors says "yes", in which case each user would be able to choose his own default editor.
> 
> 3- In the editor screens (both) there's no way to switch editors unless the admin checked the "allow users to switch editors". Changing the editor using this UI is not persistent.

I'm in agreement with all of the above, as @youknowriad described it. 

As to the question about "If using both editors...", my inclination would be to remove that option and just remember the last editor used by default.

**Comment by azaozz** [comment] 2018-11-27 23:00
Hm, OK, now I seem to be missing something. Perhaps we need to step back a bit and clear up some things :)

1. What is the purpose of this plugin? Until now it has been to disable Gutenberg and/or the Block Editor and replace them with the Classic Editor. Is this changing? And if yes, why?

2. Later on an option was added to not disable Gutenberg/Block Editor, but instead add links to create new posts and open posts for editing in the Classic Editor. This makes both editors available to the users, but has the disadvantage of some posts being "mangled" sometimes (posts started in Gutenberg and later edited in the Classic Editor often loose some blocks. That's usually not a big problem if they don't contain dynamic blocks and are not edited later in Gutenberg).

3. What do you mean by "default editor"? Does it mean both editors will be available at all times, and we will always show the "Edit in Block Editor", "Edit in Classic Editor" links, the postbox, the submenu in Gutenberg, etc.? Then there will be almost no differences regardless of which editor is chosen by the user to be the "default". The only difference I see would be which editor will be opened first when a used clicks on the Add New link in the heading on the posts list table. 

Also, if that's the case how the users will be able to disable one editor or the other? If they are not, wouldn't that be a regression from # 1 above? :)

**Comment by azaozz** [comment] 2018-11-27 23:15
> 1- In the settings screen (for admins), have these two options:
>    Choose the default editor: Two choices classic or block.
>    Choose whether to allow the users to switch editors or not (force the default editor on all users, on allow them to change their default editor)

> By default, I'd say the default editor should say "classic" and the second option should say "no" which means that for all users, the classic editor will be enforced.

OK, how would the admin options work in the four possible cases:
1. Editor = Classic, allow users = false (default).
2. Editor = Classic, allow users = true.
3. Editor = Gutenberg, allow users = false.
4. Editor = Gutenberg, allow users = true.

> 2- In the users's profile screen, there's nothing unless the "allow users to switch editors says "yes", in which case each user would be able to choose his own default editor.

What do you mean by "default editor"? Does it mean both editors are available, and all links, postbox, submenu are there? If yes, what would be the difference when the user chooses Classic vs. Gutenberg? All of the wp-admin UI will be pretty much the same with only minor differences. Do we really need to add an option for that? And if we do, how (and where) do we explain to the users how it works and why everything looks the same :)

> 3- In the editor screens (both) there's no way to switch editors unless the admin checked the "allow users to switch editors". Changing the editor using this UI is not persistent.

In this case if the admin selected Gutenberg as default editor and "do not allow to switch editors", what would this plugin do? It seems it will be pointless :) 

Or do you mean we only restrict the users to not be able to switch editors while editing a post, but let them switch from the Posts list table? Why? It will just be an inconvenience...

**Comment by youknowriad** [comment] 2018-11-28 07:48
> Editor = Classic, allow users = false (default).

There's no access to the block editor at all. The users can't switch

> Editor = Classic, allow users = true.

When you create new posts, the editor opened by default is "classic"
When you edit posts, the editor opened by default is "classic" unless the "edit with the corresponding editor" option is checked in which case it depends on the post
The user can change its default editor in its profile
The user can switch editors temporarily in the editor screens.
Links "Edit in Classic", "Edit in Gutenberg" could be available.

> Editor = Gutenberg, allow users = false.

There's no access to the classic editor (basically it's the same as if you didn't have the plugin)

> Editor = Gutenberg, allow users = true.

When you create new posts, the editor opened by default is "gutenberg"
When you edit posts, the editor opened by default is "gutenberg" unless the "edit with the corresponding editor" option is checked in which case it depends on the post
The user can change its default editor in its profile
The user can switch editors temporarily in the editor screens.
Links "Edit in Classic", "Edit in Gutenberg" could be available.

---
Does this make senses?

>  What is the purpose of this plugin? Until now it has been to disable Gutenberg and/or the Block Editor and replace them with the Classic Editor. Is this changing? And if yes, why?

This is not changing as this is the default options of the plugin, the idea is to allow the plugin to ease the transition into Gutenberg gradually. (Using this new switch options)

**Comment by azaozz** [comment] 2018-12-01 12:43
This became a kind of "run away" issue :) Started as adding a new feature (settings per user), then grew into redoing the UI, and finally into a refactoring.

Thinking it would be easier to track if we split it into couple more issues: perhaps one for the UI and another for changing how the plugin works. Opened #14 as a follow-up.

**Comment by kwight** [comment] 2018-12-01 18:12
This seems like it got more complicated than necessary; would it not work to have one admin option (radio button, user can select their own editor: yes/no) and one user option (radio button, select editor: classic/gutenberg)? The "default" site editor is chosen by the admin through the act of installing the plugin or not (not installed = Gutenberg, installed = classic).

Or maybe I've missed some subtle requirements not handled by the above?..

**Comment by azaozz** [comment] 2018-12-02 08:16
Right, the plugin has three "main modes":
1. Use Gutenberg (Block Editor) only. Equals to plugin not installed/not activated.
2. Use Classic Editor only. Plugin's default.
3. Use both Block and Classic editors.

> The "default" site editor is chosen by the admin through the act of installing the plugin or not (not installed = Gutenberg, installed = classic).

Yep, that's how it was before, in the current release v.0.5. There were only two radio buttons: "Classic" or "Both". Then added per-user settings that had the same two options (when enabled).

However the "more problematic" one is # 3 above: use both editors. In v.0.5 it was opening Gutenberg by default and had links and buttons to alternatively open each post (or create new post) in Classic. I can see how a user may want to switch that behavior, i.e. open each post in Classic by default and have links and buttons to alternatively open it in Gutenberg.

Implemented this in https://github.com/WordPress/classic-editor/commit/2b00a7b5c841bd50e621183c0d15c27499a2fffd yesterday. Now the options work pretty much like @youknowriad [described above](https://github.com/WordPress/classic-editor/issues/9#issuecomment-442351267).

In the meantime added another feature: "Remember the last editor used for each post". That was requested by the users, and is really nice to have as best is to always edit a particular post with the same editor. Also added another Yes/No option to enable it.

I'm still 50/50 if that should be an option or it should be always enabled. The reason is that it may be a bit unexpected when one post opens in Classic, another in Gutenberg (Block Editor). Another thing I'd like to add for it is show which editor will be opened for each post in the list table's "post status", similarly to how the Gutenberg plugin does it. Then, perhaps we can remove the Yes/No option. I'll try that in few min :)

**Comment by youknowriad** [comment] 2018-12-03 07:45
@kwight The subtle difference with what you propose is that a site admin won't be able to tell: "Let's use Gutenberg as a default editor but let's allow our users to switch editors if needed"

**Comment by youknowriad** [comment] 2018-12-03 07:48
I just tested the options and I'm personally satisfied with the clarity of the options at the moment. I'd consider closing this issue for now and iterate on smaller issues. What do you all think?

**Comment by azaozz** [comment] 2018-12-03 12:19
> consider closing this issue for now and iterate on smaller issues

Sure, lets move remaining things to new/smaller issues.

**Closed by azaozz** 2018-12-03 12:19 UTC
Labels: enhancement
