### ISSUE TITLE
wp-admin/post.php coming up as Page Not Found when Updating

### ISSUE THREAD

**Issue by blakespot** [WordPress/classic-editor#192] opened 2022-11-29 18:27 UTC
This has started happening rather recently. I am on WP 6.0.3. 

If I go to edit an existing, older post - one that I want to edit with Classic Editor because it was posted before the new editor arrived, when I go to Update, I get a "Page Not Found" error and the URL shows:

https://blogname.com/wp-admin/post.php

Any new post I create on this blog starts off in the Classic Editor (unsure if that's under my control). I usually start it, save it, then go edit with Block Editor. So I created a new test post and saved it (in the default Classic Editor as mentioned), then went and edited it and clicked UPDATE. I did NOT get a Page Not Found error -- the update "took" and I was taken back to the edit screen with URL of:

https://blogname.com/wp-admin/post.php?post=7368&action=edit&classic-editor

What's going on here? Is the Classic Editor now deprecated? My solution has been to edit in Block Editor and Edit as HTML, but it's difficult to negotiate. If not deprecated, any ideas what's happening here? I've made such edits in recent weeks without issue and I feel nearly certain WP has not updated itself with a security patch in that time. 

Please advise. Thanks.

bp

**Comment by azaozz** [comment] 2024-05-10 21:14
Frankly I'm not sure what's going on here either. The old Edit Post screen in WP has been deprecated for quite some time. It is in a "maintenance only" mode. This plugin, Classic Editor, that enables access to the old Edit Post screen is not deprecated and is still supported. Perhaps another plugin may be causing this?

Closing for now as it's been a long time with no additional info. Please feel free to reopen if this is still a problem that may be caused by this plugin.

**Closed by azaozz** 2024-05-10 21:14 UTC
